[project]
name = "pythonproject"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "notebook>=7.4.1",
    "pandas>=2.2.3",
    "pdfplumber>=0.11.6",
]
